package com.saulpower.GreenWireTest.database;

import java.util.List;
import de.greenrobot.dao.sync.GreenSync;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.Allergy;
import com.saulpower.GreenWireTest.database.Allergy.AllergySeverity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ALLERGY.
*/
public class AllergyDao extends AbstractDao<Allergy, Long> {

    public static final String TABLENAME = "ALLERGY";

    /**
     * Properties of entity Allergy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property DefinitionID = new Property(0, String.class, "definitionID", false, "DEFINITION_ID");
        public final static Property ExternalID = new Property(1, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property Guid = new Property(2, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property AllergiesPersonId = new Property(4, long.class, "allergiesPersonId", false, "ALLERGIES_PERSON_ID");
        public final static Property Severity = new Property(5, AllergySeverity.class, "severity", false, "SEVERITY");
        public final static Property TagString = new Property(6, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(7, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(8, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property DateLastModified = new Property(9, String.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property AllergiesGuardianId = new Property(10, long.class, "allergiesGuardianId", false, "ALLERGIES_GUARDIAN_ID");
        public final static Property SyncBaseId = new Property(11, Long.class, "syncBaseId", false, "SYNC_BASE_ID");
        public final static Property IsDeleted = new Property(12, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(13, Integer.class, "version", false, "VERSION");
        public final static Property Id = new Property(14, Long.class, "id", true, "_id");
        public final static Property AllergiesStudentId = new Property(15, long.class, "allergiesStudentId", false, "ALLERGIES_STUDENT_ID");
        public final static Property DateCreated = new Property(16, String.class, "dateCreated", false, "DATE_CREATED");
        public final static Property Treatment = new Property(17, String.class, "treatment", false, "TREATMENT");
        public final static Property Notes = new Property(18, String.class, "notes", false, "NOTES");
    };

    private DaoSession daoSession;

    private Query<Allergy> person_AllergiesQuery;

    private Query<Allergy> student_AllergiesQuery;

    private Query<Allergy> guardian_AllergiesQuery;

    public AllergyDao(DaoConfig config) {
        super(config);
    }
    
    public AllergyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ALLERGY' (" + //
                "'DEFINITION_ID' TEXT," + // 0: definitionID
                "'EXTERNAL_ID' TEXT," + // 1: externalID
                "'GUID' TEXT," + // 2: guid
                "'NAME' TEXT," + // 3: name
                "'ALLERGIES_PERSON_ID' INTEGER NOT NULL ," + // 4: allergiesPersonId
                "'SEVERITY' INTEGER," + // 5: severity
                "'TAG_STRING' TEXT," + // 6: tagString
                "'TENANT_ID' INTEGER," + // 7: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 8: saveResultSaveResultId
                "'DATE_LAST_MODIFIED' TEXT," + // 9: dateLastModified
                "'ALLERGIES_GUARDIAN_ID' INTEGER NOT NULL ," + // 10: allergiesGuardianId
                "'SYNC_BASE_ID' INTEGER REFERENCES 'SYNC_BASE'('SYNC_BASE_ID') ," + // 11: syncBaseId
                "'IS_DELETED' INTEGER," + // 12: isDeleted
                "'VERSION' INTEGER," + // 13: version
                "'_id' INTEGER PRIMARY KEY ," + // 14: id
                "'ALLERGIES_STUDENT_ID' INTEGER NOT NULL ," + // 15: allergiesStudentId
                "'DATE_CREATED' TEXT," + // 16: dateCreated
                "'TREATMENT' TEXT," + // 17: treatment
                "'NOTES' TEXT);"); // 18: notes
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ALLERGY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Allergy entity) {
        stmt.clearBindings();
 
        String definitionID = entity.getDefinitionID();
        if (definitionID != null) {
            stmt.bindString(1, definitionID);
        }
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(2, externalID);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(3, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
        stmt.bindLong(5, entity.getAllergiesPersonId());
 
        AllergySeverity severity = entity.getSeverity();
        if (severity != null) {
            stmt.bindLong(6, severity.getValue());
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(7, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(8, tenantID);
        }
        stmt.bindLong(9, entity.getSaveResultSaveResultId());
 
        String dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindString(10, dateLastModified);
        }
        stmt.bindLong(11, entity.getAllergiesGuardianId());
 
        Long syncBaseId = entity.getSyncBaseId();
        if (syncBaseId != null) {
            stmt.bindLong(12, syncBaseId);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(13, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(14, version);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(15, id);
        }
        stmt.bindLong(16, entity.getAllergiesStudentId());
 
        String dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindString(17, dateCreated);
        }
 
        String treatment = entity.getTreatment();
        if (treatment != null) {
            stmt.bindString(18, treatment);
        }
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(19, notes);
        }
    }

    @Override
    protected void attachEntity(Allergy entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14);
    }    

    /** @inheritdoc */
    @Override
    public Allergy readEntity(Cursor cursor, int offset) {
        Allergy entity = new Allergy( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // definitionID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // externalID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // guid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.getLong(offset + 4), // allergiesPersonId
            cursor.isNull(offset + 5) ? null : AllergySeverity.fromInt(cursor.getLong(offset + 5)), // severity
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tagString
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // tenantID
            cursor.getLong(offset + 8), // saveResultSaveResultId
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // dateLastModified
            cursor.getLong(offset + 10), // allergiesGuardianId
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // syncBaseId
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isDeleted
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // version
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // id
            cursor.getLong(offset + 15), // allergiesStudentId
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // dateCreated
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // treatment
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18) // notes
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Allergy entity, int offset) {
        entity.setDefinitionID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setExternalID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGuid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAllergiesPersonId(cursor.getLong(offset + 4));
        entity.setSeverity(cursor.isNull(offset + 5) ? null : AllergySeverity.fromInt(cursor.getLong(offset + 5)));
        entity.setTagString(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTenantID(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 8));
        entity.setDateLastModified(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAllergiesGuardianId(cursor.getLong(offset + 10));
        entity.setSyncBaseId(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setIsDeleted(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setVersion(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setId(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setAllergiesStudentId(cursor.getLong(offset + 15));
        entity.setDateCreated(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTreatment(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setNotes(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Allergy entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Allergy entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "allergies" to-many relationship of Person. */
    public List<Allergy> _queryPerson_Allergies(long allergiesPersonId) {
        synchronized (this) {
            if (person_AllergiesQuery == null) {
                QueryBuilder<Allergy> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AllergiesPersonId.eq(null));
                person_AllergiesQuery = queryBuilder.build();
            }
        }
        Query<Allergy> query = person_AllergiesQuery.forCurrentThread();
        query.setParameter(0, allergiesPersonId);
        return query.list();
    }

    /** Internal query to resolve the "allergies" to-many relationship of Student. */
    public List<Allergy> _queryStudent_Allergies(long allergiesStudentId) {
        synchronized (this) {
            if (student_AllergiesQuery == null) {
                QueryBuilder<Allergy> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AllergiesStudentId.eq(null));
                student_AllergiesQuery = queryBuilder.build();
            }
        }
        Query<Allergy> query = student_AllergiesQuery.forCurrentThread();
        query.setParameter(0, allergiesStudentId);
        return query.list();
    }

    /** Internal query to resolve the "allergies" to-many relationship of Guardian. */
    public List<Allergy> _queryGuardian_Allergies(long allergiesGuardianId) {
        synchronized (this) {
            if (guardian_AllergiesQuery == null) {
                QueryBuilder<Allergy> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AllergiesGuardianId.eq(null));
                guardian_AllergiesQuery = queryBuilder.build();
            }
        }
        Query<Allergy> query = guardian_AllergiesQuery.forCurrentThread();
        query.setParameter(0, allergiesGuardianId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM ALLERGY T");
            builder.append(" LEFT JOIN SAVE_RESULT T0 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Allergy loadCurrentDeep(Cursor cursor, boolean lock) {
        Allergy entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public Allergy loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Allergy> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Allergy> list = new ArrayList<Allergy>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Allergy> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Allergy> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
    @Override
    protected void onPreInsertEntity(Allergy entity) {
        entity.insertBase(daoSession.getSyncBaseDao());
        entity.setSyncBaseId(entity.getSyncBaseId());
    }

    @Override
    protected void onPreLoadEntity(Allergy entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreRefreshEntity(Allergy entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreUpdateEntity(Allergy entity) {
        entity.updateBase(daoSession.getSyncBaseDao());
    }

    @Override
    protected void onPreDeleteEntity(Allergy entity) {
        entity.deleteBase(daoSession.getSyncBaseDao());
    }

    static {
        GreenSync.registerListTypeToken("Allergy", new TypeToken<List<Allergy>>(){}.getType());
        GreenSync.registerTypeToken("Allergy", Allergy.class);
    }

}
