package com.saulpower.GreenWireTest.database;

import java.util.List;
import de.greenrobot.dao.sync.GreenSync;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.Immunization;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table IMMUNIZATION.
*/
public class ImmunizationDao extends AbstractDao<Immunization, Long> {

    public static final String TABLENAME = "IMMUNIZATION";

    /**
     * Properties of entity Immunization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PersonPersonId = new Property(0, long.class, "personPersonId", false, "PERSON_PERSON_ID");
        public final static Property ImmunizationsGuardianId = new Property(1, long.class, "immunizationsGuardianId", false, "IMMUNIZATIONS_GUARDIAN_ID");
        public final static Property DefinitionID = new Property(2, String.class, "definitionID", false, "DEFINITION_ID");
        public final static Property ExternalID = new Property(3, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property Guid = new Property(4, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property TagString = new Property(6, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(7, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(8, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property ImmunizationsStudentId = new Property(9, long.class, "immunizationsStudentId", false, "IMMUNIZATIONS_STUDENT_ID");
        public final static Property DateLastModified = new Property(10, String.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property DefinitionImmunizationDefinitionId = new Property(11, long.class, "definitionImmunizationDefinitionId", false, "DEFINITION_IMMUNIZATION_DEFINITION_ID");
        public final static Property SyncBaseId = new Property(12, Long.class, "syncBaseId", false, "SYNC_BASE_ID");
        public final static Property IsDeleted = new Property(13, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(14, Integer.class, "version", false, "VERSION");
        public final static Property Id = new Property(15, Long.class, "id", true, "_id");
        public final static Property ImmunizationsPersonId = new Property(16, long.class, "immunizationsPersonId", false, "IMMUNIZATIONS_PERSON_ID");
        public final static Property DateCreated = new Property(17, String.class, "dateCreated", false, "DATE_CREATED");
        public final static Property ImmunizationsImmunizationDefinitionId = new Property(18, long.class, "immunizationsImmunizationDefinitionId", false, "IMMUNIZATIONS_IMMUNIZATION_DEFINITION_ID");
    };

    private DaoSession daoSession;

    private Query<Immunization> person_ImmunizationsQuery;

    private Query<Immunization> student_ImmunizationsQuery;

    private Query<Immunization> immunizationDefinition_ImmunizationsQuery;

    private Query<Immunization> guardian_ImmunizationsQuery;

    public ImmunizationDao(DaoConfig config) {
        super(config);
    }
    
    public ImmunizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'IMMUNIZATION' (" + //
                "'PERSON_PERSON_ID' INTEGER NOT NULL ," + // 0: personPersonId
                "'IMMUNIZATIONS_GUARDIAN_ID' INTEGER NOT NULL ," + // 1: immunizationsGuardianId
                "'DEFINITION_ID' TEXT," + // 2: definitionID
                "'EXTERNAL_ID' TEXT," + // 3: externalID
                "'GUID' TEXT," + // 4: guid
                "'NAME' TEXT," + // 5: name
                "'TAG_STRING' TEXT," + // 6: tagString
                "'TENANT_ID' INTEGER," + // 7: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 8: saveResultSaveResultId
                "'IMMUNIZATIONS_STUDENT_ID' INTEGER NOT NULL ," + // 9: immunizationsStudentId
                "'DATE_LAST_MODIFIED' TEXT," + // 10: dateLastModified
                "'DEFINITION_IMMUNIZATION_DEFINITION_ID' INTEGER NOT NULL ," + // 11: definitionImmunizationDefinitionId
                "'SYNC_BASE_ID' INTEGER REFERENCES 'SYNC_BASE'('SYNC_BASE_ID') ," + // 12: syncBaseId
                "'IS_DELETED' INTEGER," + // 13: isDeleted
                "'VERSION' INTEGER," + // 14: version
                "'_id' INTEGER PRIMARY KEY ," + // 15: id
                "'IMMUNIZATIONS_PERSON_ID' INTEGER NOT NULL ," + // 16: immunizationsPersonId
                "'DATE_CREATED' TEXT," + // 17: dateCreated
                "'IMMUNIZATIONS_IMMUNIZATION_DEFINITION_ID' INTEGER NOT NULL );"); // 18: immunizationsImmunizationDefinitionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'IMMUNIZATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Immunization entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getPersonPersonId());
        stmt.bindLong(2, entity.getImmunizationsGuardianId());
 
        String definitionID = entity.getDefinitionID();
        if (definitionID != null) {
            stmt.bindString(3, definitionID);
        }
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(4, externalID);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(5, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(7, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(8, tenantID);
        }
        stmt.bindLong(9, entity.getSaveResultSaveResultId());
        stmt.bindLong(10, entity.getImmunizationsStudentId());
 
        String dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindString(11, dateLastModified);
        }
        stmt.bindLong(12, entity.getDefinitionImmunizationDefinitionId());
 
        Long syncBaseId = entity.getSyncBaseId();
        if (syncBaseId != null) {
            stmt.bindLong(13, syncBaseId);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(14, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(15, version);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(16, id);
        }
        stmt.bindLong(17, entity.getImmunizationsPersonId());
 
        String dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindString(18, dateCreated);
        }
        stmt.bindLong(19, entity.getImmunizationsImmunizationDefinitionId());
    }

    @Override
    protected void attachEntity(Immunization entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15);
    }    

    /** @inheritdoc */
    @Override
    public Immunization readEntity(Cursor cursor, int offset) {
        Immunization entity = new Immunization( //
            cursor.getLong(offset + 0), // personPersonId
            cursor.getLong(offset + 1), // immunizationsGuardianId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // definitionID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // externalID
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // guid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tagString
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // tenantID
            cursor.getLong(offset + 8), // saveResultSaveResultId
            cursor.getLong(offset + 9), // immunizationsStudentId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // dateLastModified
            cursor.getLong(offset + 11), // definitionImmunizationDefinitionId
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // syncBaseId
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // isDeleted
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // version
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // id
            cursor.getLong(offset + 16), // immunizationsPersonId
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dateCreated
            cursor.getLong(offset + 18) // immunizationsImmunizationDefinitionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Immunization entity, int offset) {
        entity.setPersonPersonId(cursor.getLong(offset + 0));
        entity.setImmunizationsGuardianId(cursor.getLong(offset + 1));
        entity.setDefinitionID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExternalID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGuid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTagString(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTenantID(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 8));
        entity.setImmunizationsStudentId(cursor.getLong(offset + 9));
        entity.setDateLastModified(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setDefinitionImmunizationDefinitionId(cursor.getLong(offset + 11));
        entity.setSyncBaseId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setIsDeleted(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setVersion(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setId(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setImmunizationsPersonId(cursor.getLong(offset + 16));
        entity.setDateCreated(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setImmunizationsImmunizationDefinitionId(cursor.getLong(offset + 18));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Immunization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Immunization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "immunizations" to-many relationship of Person. */
    public List<Immunization> _queryPerson_Immunizations(long immunizationsPersonId) {
        synchronized (this) {
            if (person_ImmunizationsQuery == null) {
                QueryBuilder<Immunization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ImmunizationsPersonId.eq(null));
                person_ImmunizationsQuery = queryBuilder.build();
            }
        }
        Query<Immunization> query = person_ImmunizationsQuery.forCurrentThread();
        query.setParameter(0, immunizationsPersonId);
        return query.list();
    }

    /** Internal query to resolve the "immunizations" to-many relationship of Student. */
    public List<Immunization> _queryStudent_Immunizations(long immunizationsStudentId) {
        synchronized (this) {
            if (student_ImmunizationsQuery == null) {
                QueryBuilder<Immunization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ImmunizationsStudentId.eq(null));
                student_ImmunizationsQuery = queryBuilder.build();
            }
        }
        Query<Immunization> query = student_ImmunizationsQuery.forCurrentThread();
        query.setParameter(0, immunizationsStudentId);
        return query.list();
    }

    /** Internal query to resolve the "immunizations" to-many relationship of ImmunizationDefinition. */
    public List<Immunization> _queryImmunizationDefinition_Immunizations(long immunizationsImmunizationDefinitionId) {
        synchronized (this) {
            if (immunizationDefinition_ImmunizationsQuery == null) {
                QueryBuilder<Immunization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ImmunizationsImmunizationDefinitionId.eq(null));
                immunizationDefinition_ImmunizationsQuery = queryBuilder.build();
            }
        }
        Query<Immunization> query = immunizationDefinition_ImmunizationsQuery.forCurrentThread();
        query.setParameter(0, immunizationsImmunizationDefinitionId);
        return query.list();
    }

    /** Internal query to resolve the "immunizations" to-many relationship of Guardian. */
    public List<Immunization> _queryGuardian_Immunizations(long immunizationsGuardianId) {
        synchronized (this) {
            if (guardian_ImmunizationsQuery == null) {
                QueryBuilder<Immunization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ImmunizationsGuardianId.eq(null));
                guardian_ImmunizationsQuery = queryBuilder.build();
            }
        }
        Query<Immunization> query = guardian_ImmunizationsQuery.forCurrentThread();
        query.setParameter(0, immunizationsGuardianId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getImmunizationDefinitionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPersonDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM IMMUNIZATION T");
            builder.append(" LEFT JOIN IMMUNIZATION_DEFINITION T0 ON T.'DEFINITION_IMMUNIZATION_DEFINITION_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PERSON T1 ON T.'PERSON_PERSON_ID'=T1.'_id'");
            builder.append(" LEFT JOIN SAVE_RESULT T2 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Immunization loadCurrentDeep(Cursor cursor, boolean lock) {
        Immunization entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ImmunizationDefinition definition = loadCurrentOther(daoSession.getImmunizationDefinitionDao(), cursor, offset);
         if(definition != null) {
            entity.setDefinition(definition);
        }
        offset += daoSession.getImmunizationDefinitionDao().getAllColumns().length;

        Person person = loadCurrentOther(daoSession.getPersonDao(), cursor, offset);
         if(person != null) {
            entity.setPerson(person);
        }
        offset += daoSession.getPersonDao().getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public Immunization loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Immunization> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Immunization> list = new ArrayList<Immunization>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Immunization> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Immunization> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
    @Override
    protected void onPreInsertEntity(Immunization entity) {
        entity.insertBase(daoSession.getSyncBaseDao());
        entity.setSyncBaseId(entity.getSyncBaseId());
    }

    @Override
    protected void onPreLoadEntity(Immunization entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreRefreshEntity(Immunization entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreUpdateEntity(Immunization entity) {
        entity.updateBase(daoSession.getSyncBaseDao());
    }

    @Override
    protected void onPreDeleteEntity(Immunization entity) {
        entity.deleteBase(daoSession.getSyncBaseDao());
    }

    static {
        GreenSync.registerListTypeToken("Immunization", new TypeToken<List<Immunization>>(){}.getType());
        GreenSync.registerTypeToken("Immunization", Immunization.class);
    }

}
