package com.saulpower.GreenWireTest.database;

import java.util.List;
import de.greenrobot.dao.sync.GreenSync;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.LedgerItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LEDGER_ITEM.
*/
public class LedgerItemDao extends AbstractDao<LedgerItem, Long> {

    public static final String TABLENAME = "LEDGER_ITEM";

    /**
     * Properties of entity LedgerItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property LedgerItemsLedgerAccountId = new Property(0, long.class, "ledgerItemsLedgerAccountId", false, "LEDGER_ITEMS_LEDGER_ACCOUNT_ID");
        public final static Property PersonPersonId = new Property(1, long.class, "personPersonId", false, "PERSON_PERSON_ID");
        public final static Property PostingDate = new Property(2, String.class, "postingDate", false, "POSTING_DATE");
        public final static Property ExternalID = new Property(3, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property IsVoid = new Property(4, Boolean.class, "isVoid", false, "IS_VOID");
        public final static Property Guid = new Property(5, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property TagString = new Property(7, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(8, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(9, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property Debit = new Property(10, Float.class, "debit", false, "DEBIT");
        public final static Property DateLastModified = new Property(11, String.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property SyncBaseId = new Property(12, Long.class, "syncBaseId", false, "SYNC_BASE_ID");
        public final static Property Credit = new Property(13, Float.class, "credit", false, "CREDIT");
        public final static Property IsDeleted = new Property(14, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(15, Integer.class, "version", false, "VERSION");
        public final static Property Id = new Property(16, Long.class, "id", true, "_id");
        public final static Property LedgerAccountLedgerAccountId = new Property(17, long.class, "ledgerAccountLedgerAccountId", false, "LEDGER_ACCOUNT_LEDGER_ACCOUNT_ID");
        public final static Property DateCreated = new Property(18, String.class, "dateCreated", false, "DATE_CREATED");
        public final static Property Notes = new Property(19, String.class, "notes", false, "NOTES");
    };

    private DaoSession daoSession;

    private Query<LedgerItem> ledgerAccount_LedgerItemsQuery;

    public LedgerItemDao(DaoConfig config) {
        super(config);
    }
    
    public LedgerItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LEDGER_ITEM' (" + //
                "'LEDGER_ITEMS_LEDGER_ACCOUNT_ID' INTEGER NOT NULL ," + // 0: ledgerItemsLedgerAccountId
                "'PERSON_PERSON_ID' INTEGER NOT NULL ," + // 1: personPersonId
                "'POSTING_DATE' TEXT," + // 2: postingDate
                "'EXTERNAL_ID' TEXT," + // 3: externalID
                "'IS_VOID' INTEGER," + // 4: isVoid
                "'GUID' TEXT," + // 5: guid
                "'NAME' TEXT," + // 6: name
                "'TAG_STRING' TEXT," + // 7: tagString
                "'TENANT_ID' INTEGER," + // 8: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 9: saveResultSaveResultId
                "'DEBIT' REAL," + // 10: debit
                "'DATE_LAST_MODIFIED' TEXT," + // 11: dateLastModified
                "'SYNC_BASE_ID' INTEGER REFERENCES 'SYNC_BASE'('SYNC_BASE_ID') ," + // 12: syncBaseId
                "'CREDIT' REAL," + // 13: credit
                "'IS_DELETED' INTEGER," + // 14: isDeleted
                "'VERSION' INTEGER," + // 15: version
                "'_id' INTEGER PRIMARY KEY ," + // 16: id
                "'LEDGER_ACCOUNT_LEDGER_ACCOUNT_ID' INTEGER NOT NULL ," + // 17: ledgerAccountLedgerAccountId
                "'DATE_CREATED' TEXT," + // 18: dateCreated
                "'NOTES' TEXT);"); // 19: notes
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LEDGER_ITEM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LedgerItem entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLedgerItemsLedgerAccountId());
        stmt.bindLong(2, entity.getPersonPersonId());
 
        String postingDate = entity.getPostingDate();
        if (postingDate != null) {
            stmt.bindString(3, postingDate);
        }
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(4, externalID);
        }
 
        Boolean isVoid = entity.getIsVoid();
        if (isVoid != null) {
            stmt.bindLong(5, isVoid ? 1l: 0l);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(6, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(8, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(9, tenantID);
        }
        stmt.bindLong(10, entity.getSaveResultSaveResultId());
 
        Float debit = entity.getDebit();
        if (debit != null) {
            stmt.bindDouble(11, debit);
        }
 
        String dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindString(12, dateLastModified);
        }
 
        Long syncBaseId = entity.getSyncBaseId();
        if (syncBaseId != null) {
            stmt.bindLong(13, syncBaseId);
        }
 
        Float credit = entity.getCredit();
        if (credit != null) {
            stmt.bindDouble(14, credit);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(15, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(16, version);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(17, id);
        }
        stmt.bindLong(18, entity.getLedgerAccountLedgerAccountId());
 
        String dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindString(19, dateCreated);
        }
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(20, notes);
        }
    }

    @Override
    protected void attachEntity(LedgerItem entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16);
    }    

    /** @inheritdoc */
    @Override
    public LedgerItem readEntity(Cursor cursor, int offset) {
        LedgerItem entity = new LedgerItem( //
            cursor.getLong(offset + 0), // ledgerItemsLedgerAccountId
            cursor.getLong(offset + 1), // personPersonId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // postingDate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // externalID
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isVoid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // guid
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tagString
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // tenantID
            cursor.getLong(offset + 9), // saveResultSaveResultId
            cursor.isNull(offset + 10) ? null : cursor.getFloat(offset + 10), // debit
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // dateLastModified
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // syncBaseId
            cursor.isNull(offset + 13) ? null : cursor.getFloat(offset + 13), // credit
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0, // isDeleted
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15), // version
            cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16), // id
            cursor.getLong(offset + 17), // ledgerAccountLedgerAccountId
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // dateCreated
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19) // notes
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LedgerItem entity, int offset) {
        entity.setLedgerItemsLedgerAccountId(cursor.getLong(offset + 0));
        entity.setPersonPersonId(cursor.getLong(offset + 1));
        entity.setPostingDate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setExternalID(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsVoid(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setGuid(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTagString(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTenantID(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 9));
        entity.setDebit(cursor.isNull(offset + 10) ? null : cursor.getFloat(offset + 10));
        entity.setDateLastModified(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setSyncBaseId(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setCredit(cursor.isNull(offset + 13) ? null : cursor.getFloat(offset + 13));
        entity.setIsDeleted(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0);
        entity.setVersion(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
        entity.setId(cursor.isNull(offset + 16) ? null : cursor.getLong(offset + 16));
        entity.setLedgerAccountLedgerAccountId(cursor.getLong(offset + 17));
        entity.setDateCreated(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setNotes(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LedgerItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(LedgerItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ledgerItems" to-many relationship of LedgerAccount. */
    public List<LedgerItem> _queryLedgerAccount_LedgerItems(long ledgerItemsLedgerAccountId) {
        synchronized (this) {
            if (ledgerAccount_LedgerItemsQuery == null) {
                QueryBuilder<LedgerItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.LedgerItemsLedgerAccountId.eq(null));
                ledgerAccount_LedgerItemsQuery = queryBuilder.build();
            }
        }
        Query<LedgerItem> query = ledgerAccount_LedgerItemsQuery.forCurrentThread();
        query.setParameter(0, ledgerItemsLedgerAccountId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLedgerAccountDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getPersonDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM LEDGER_ITEM T");
            builder.append(" LEFT JOIN LEDGER_ACCOUNT T0 ON T.'LEDGER_ACCOUNT_LEDGER_ACCOUNT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN PERSON T1 ON T.'PERSON_PERSON_ID'=T1.'_id'");
            builder.append(" LEFT JOIN SAVE_RESULT T2 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LedgerItem loadCurrentDeep(Cursor cursor, boolean lock) {
        LedgerItem entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LedgerAccount ledgerAccount = loadCurrentOther(daoSession.getLedgerAccountDao(), cursor, offset);
         if(ledgerAccount != null) {
            entity.setLedgerAccount(ledgerAccount);
        }
        offset += daoSession.getLedgerAccountDao().getAllColumns().length;

        Person person = loadCurrentOther(daoSession.getPersonDao(), cursor, offset);
         if(person != null) {
            entity.setPerson(person);
        }
        offset += daoSession.getPersonDao().getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public LedgerItem loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LedgerItem> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LedgerItem> list = new ArrayList<LedgerItem>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LedgerItem> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LedgerItem> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
    @Override
    protected void onPreInsertEntity(LedgerItem entity) {
        entity.insertBase(daoSession.getSyncBaseDao());
        entity.setSyncBaseId(entity.getSyncBaseId());
    }

    @Override
    protected void onPreLoadEntity(LedgerItem entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreRefreshEntity(LedgerItem entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreUpdateEntity(LedgerItem entity) {
        entity.updateBase(daoSession.getSyncBaseDao());
    }

    @Override
    protected void onPreDeleteEntity(LedgerItem entity) {
        entity.deleteBase(daoSession.getSyncBaseDao());
    }

    static {
        GreenSync.registerListTypeToken("LedgerItem", new TypeToken<List<LedgerItem>>(){}.getType());
        GreenSync.registerTypeToken("LedgerItem", LedgerItem.class);
    }

}
