package com.saulpower.GreenWireTest.database;

import java.util.List;
import de.greenrobot.dao.sync.GreenSync;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.OUBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table OUBASE.
*/
public class OUBaseDao extends AbstractDao<OUBase, Long> {

    public static final String TABLENAME = "OUBASE";

    /**
     * Properties of entity OUBase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ExternalID = new Property(0, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property Guid = new Property(1, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property ParentOUBaseId = new Property(3, long.class, "parentOUBaseId", false, "PARENT_OUBASE_ID");
        public final static Property TagString = new Property(4, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(5, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(6, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property DateLastModified = new Property(7, String.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property Number = new Property(8, String.class, "number", false, "NUMBER");
        public final static Property SyncBaseId = new Property(9, Long.class, "syncBaseId", false, "SYNC_BASE_ID");
        public final static Property ChildrenCenterId = new Property(10, long.class, "childrenCenterId", false, "CHILDREN_CENTER_ID");
        public final static Property IsDeleted = new Property(11, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(12, Integer.class, "version", false, "VERSION");
        public final static Property ChildrenOUId = new Property(13, long.class, "childrenOUId", false, "CHILDREN_OUID");
        public final static Property Id = new Property(14, Long.class, "id", true, "_id");
        public final static Property ParentID = new Property(15, String.class, "parentID", false, "PARENT_ID");
        public final static Property ChildrenOUBaseId = new Property(16, long.class, "childrenOUBaseId", false, "CHILDREN_OUBASE_ID");
        public final static Property DateCreated = new Property(17, String.class, "dateCreated", false, "DATE_CREATED");
        public final static Property IsActive = new Property(18, Boolean.class, "isActive", false, "IS_ACTIVE");
    };

    private DaoSession daoSession;

    private Query<OUBase> center_ChildrenQuery;

    private Query<OUBase> oU_ChildrenQuery;

    private Query<OUBase> oUBase_ChildrenQuery;

    public OUBaseDao(DaoConfig config) {
        super(config);
    }
    
    public OUBaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'OUBASE' (" + //
                "'EXTERNAL_ID' TEXT," + // 0: externalID
                "'GUID' TEXT," + // 1: guid
                "'NAME' TEXT," + // 2: name
                "'PARENT_OUBASE_ID' INTEGER NOT NULL ," + // 3: parentOUBaseId
                "'TAG_STRING' TEXT," + // 4: tagString
                "'TENANT_ID' INTEGER," + // 5: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 6: saveResultSaveResultId
                "'DATE_LAST_MODIFIED' TEXT," + // 7: dateLastModified
                "'NUMBER' TEXT," + // 8: number
                "'SYNC_BASE_ID' INTEGER REFERENCES 'SYNC_BASE'('SYNC_BASE_ID') ," + // 9: syncBaseId
                "'CHILDREN_CENTER_ID' INTEGER NOT NULL ," + // 10: childrenCenterId
                "'IS_DELETED' INTEGER," + // 11: isDeleted
                "'VERSION' INTEGER," + // 12: version
                "'CHILDREN_OUID' INTEGER NOT NULL ," + // 13: childrenOUId
                "'_id' INTEGER PRIMARY KEY ," + // 14: id
                "'PARENT_ID' TEXT," + // 15: parentID
                "'CHILDREN_OUBASE_ID' INTEGER NOT NULL ," + // 16: childrenOUBaseId
                "'DATE_CREATED' TEXT," + // 17: dateCreated
                "'IS_ACTIVE' INTEGER);"); // 18: isActive
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'OUBASE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, OUBase entity) {
        stmt.clearBindings();
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(1, externalID);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(2, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getParentOUBaseId());
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(5, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(6, tenantID);
        }
        stmt.bindLong(7, entity.getSaveResultSaveResultId());
 
        String dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindString(8, dateLastModified);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(9, number);
        }
 
        Long syncBaseId = entity.getSyncBaseId();
        if (syncBaseId != null) {
            stmt.bindLong(10, syncBaseId);
        }
        stmt.bindLong(11, entity.getChildrenCenterId());
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(12, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(13, version);
        }
        stmt.bindLong(14, entity.getChildrenOUId());
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(15, id);
        }
 
        String parentID = entity.getParentID();
        if (parentID != null) {
            stmt.bindString(16, parentID);
        }
        stmt.bindLong(17, entity.getChildrenOUBaseId());
 
        String dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindString(18, dateCreated);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(19, isActive ? 1l: 0l);
        }
    }

    @Override
    protected void attachEntity(OUBase entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14);
    }    

    /** @inheritdoc */
    @Override
    public OUBase readEntity(Cursor cursor, int offset) {
        OUBase entity = new OUBase( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // externalID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // guid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getLong(offset + 3), // parentOUBaseId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tagString
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // tenantID
            cursor.getLong(offset + 6), // saveResultSaveResultId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // dateLastModified
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // number
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // syncBaseId
            cursor.getLong(offset + 10), // childrenCenterId
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isDeleted
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // version
            cursor.getLong(offset + 13), // childrenOUId
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14), // id
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // parentID
            cursor.getLong(offset + 16), // childrenOUBaseId
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // dateCreated
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0 // isActive
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, OUBase entity, int offset) {
        entity.setExternalID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParentOUBaseId(cursor.getLong(offset + 3));
        entity.setTagString(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTenantID(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 6));
        entity.setDateLastModified(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setSyncBaseId(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setChildrenCenterId(cursor.getLong(offset + 10));
        entity.setIsDeleted(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setVersion(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setChildrenOUId(cursor.getLong(offset + 13));
        entity.setId(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
        entity.setParentID(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setChildrenOUBaseId(cursor.getLong(offset + 16));
        entity.setDateCreated(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setIsActive(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(OUBase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(OUBase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "children" to-many relationship of Center. */
    public List<OUBase> _queryCenter_Children(long childrenCenterId) {
        synchronized (this) {
            if (center_ChildrenQuery == null) {
                QueryBuilder<OUBase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChildrenCenterId.eq(null));
                center_ChildrenQuery = queryBuilder.build();
            }
        }
        Query<OUBase> query = center_ChildrenQuery.forCurrentThread();
        query.setParameter(0, childrenCenterId);
        return query.list();
    }

    /** Internal query to resolve the "children" to-many relationship of OU. */
    public List<OUBase> _queryOU_Children(long childrenOUId) {
        synchronized (this) {
            if (oU_ChildrenQuery == null) {
                QueryBuilder<OUBase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChildrenOUId.eq(null));
                oU_ChildrenQuery = queryBuilder.build();
            }
        }
        Query<OUBase> query = oU_ChildrenQuery.forCurrentThread();
        query.setParameter(0, childrenOUId);
        return query.list();
    }

    /** Internal query to resolve the "children" to-many relationship of OUBase. */
    public List<OUBase> _queryOUBase_Children(long childrenOUBaseId) {
        synchronized (this) {
            if (oUBase_ChildrenQuery == null) {
                QueryBuilder<OUBase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChildrenOUBaseId.eq(null));
                oUBase_ChildrenQuery = queryBuilder.build();
            }
        }
        Query<OUBase> query = oUBase_ChildrenQuery.forCurrentThread();
        query.setParameter(0, childrenOUBaseId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getOUBaseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM OUBASE T");
            builder.append(" LEFT JOIN OUBASE T0 ON T.'PARENT_OUBASE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN SAVE_RESULT T1 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected OUBase loadCurrentDeep(Cursor cursor, boolean lock) {
        OUBase entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        OUBase parent = loadCurrentOther(daoSession.getOUBaseDao(), cursor, offset);
         if(parent != null) {
            entity.setParent(parent);
        }
        offset += daoSession.getOUBaseDao().getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public OUBase loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<OUBase> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<OUBase> list = new ArrayList<OUBase>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<OUBase> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<OUBase> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
    @Override
    protected void onPreInsertEntity(OUBase entity) {
        entity.insertBase(daoSession.getSyncBaseDao());
        entity.setSyncBaseId(entity.getSyncBaseId());
    }

    @Override
    protected void onPreLoadEntity(OUBase entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreRefreshEntity(OUBase entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreUpdateEntity(OUBase entity) {
        entity.updateBase(daoSession.getSyncBaseDao());
    }

    @Override
    protected void onPreDeleteEntity(OUBase entity) {
        entity.deleteBase(daoSession.getSyncBaseDao());
    }

    static {
        GreenSync.registerListTypeToken("OUBase", new TypeToken<List<OUBase>>(){}.getType());
        GreenSync.registerTypeToken("OUBase", OUBase.class);
    }

}
