package com.saulpower.GreenWireTest.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.PayrollDefinition;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PAYROLL_DEFINITION.
*/
public class PayrollDefinitionDao extends AbstractDao<PayrollDefinition, Long> {

    public static final String TABLENAME = "PAYROLL_DEFINITION";

    /**
     * Properties of entity PayrollDefinition.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Guid = new Property(0, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property ExternalID = new Property(2, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property TagString = new Property(3, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(4, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(5, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property DateLastModified = new Property(6, Long.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property IsDeleted = new Property(7, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property StartDate = new Property(8, Long.class, "startDate", false, "START_DATE");
        public final static Property Version = new Property(9, Integer.class, "version", false, "VERSION");
        public final static Property Id = new Property(10, Long.class, "id", true, "_id");
        public final static Property PayrollDefinitionsEmployeeFileId = new Property(11, long.class, "payrollDefinitionsEmployeeFileId", false, "PAYROLL_DEFINITIONS_EMPLOYEE_FILE_ID");
        public final static Property DateCreated = new Property(12, Long.class, "dateCreated", false, "DATE_CREATED");
        public final static Property IsActive = new Property(13, Boolean.class, "isActive", false, "IS_ACTIVE");
        public final static Property EndDate = new Property(14, Long.class, "endDate", false, "END_DATE");
    };

    private DaoSession daoSession;

    private Query<PayrollDefinition> employeeFile_PayrollDefinitionsQuery;

    public PayrollDefinitionDao(DaoConfig config) {
        super(config);
    }
    
    public PayrollDefinitionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PAYROLL_DEFINITION' (" + //
                "'GUID' TEXT," + // 0: guid
                "'NAME' TEXT," + // 1: name
                "'EXTERNAL_ID' TEXT," + // 2: externalID
                "'TAG_STRING' TEXT," + // 3: tagString
                "'TENANT_ID' INTEGER," + // 4: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 5: saveResultSaveResultId
                "'DATE_LAST_MODIFIED' INTEGER," + // 6: dateLastModified
                "'IS_DELETED' INTEGER," + // 7: isDeleted
                "'START_DATE' INTEGER," + // 8: startDate
                "'VERSION' INTEGER," + // 9: version
                "'_id' INTEGER PRIMARY KEY ," + // 10: id
                "'PAYROLL_DEFINITIONS_EMPLOYEE_FILE_ID' INTEGER NOT NULL ," + // 11: payrollDefinitionsEmployeeFileId
                "'DATE_CREATED' INTEGER," + // 12: dateCreated
                "'IS_ACTIVE' INTEGER," + // 13: isActive
                "'END_DATE' INTEGER);"); // 14: endDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PAYROLL_DEFINITION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PayrollDefinition entity) {
        stmt.clearBindings();
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(1, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(3, externalID);
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(4, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(5, tenantID);
        }
        stmt.bindLong(6, entity.getSaveResultSaveResultId());
 
        Long dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindLong(7, dateLastModified);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(8, isDeleted ? 1l: 0l);
        }
 
        Long startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindLong(9, startDate);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(10, version);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(11, id);
        }
        stmt.bindLong(12, entity.getPayrollDefinitionsEmployeeFileId());
 
        Long dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(13, dateCreated);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(14, isActive ? 1l: 0l);
        }
 
        Long endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindLong(15, endDate);
        }
    }

    @Override
    protected void attachEntity(PayrollDefinition entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10);
    }    

    /** @inheritdoc */
    @Override
    public PayrollDefinition readEntity(Cursor cursor, int offset) {
        PayrollDefinition entity = new PayrollDefinition( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // guid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // externalID
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tagString
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // tenantID
            cursor.getLong(offset + 5), // saveResultSaveResultId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // dateLastModified
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0, // isDeleted
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // startDate
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // version
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // id
            cursor.getLong(offset + 11), // payrollDefinitionsEmployeeFileId
            cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12), // dateCreated
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // isActive
            cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14) // endDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PayrollDefinition entity, int offset) {
        entity.setGuid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExternalID(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTagString(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTenantID(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 5));
        entity.setDateLastModified(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setIsDeleted(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
        entity.setStartDate(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setVersion(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setId(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setPayrollDefinitionsEmployeeFileId(cursor.getLong(offset + 11));
        entity.setDateCreated(cursor.isNull(offset + 12) ? null : cursor.getLong(offset + 12));
        entity.setIsActive(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setEndDate(cursor.isNull(offset + 14) ? null : cursor.getLong(offset + 14));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PayrollDefinition entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PayrollDefinition entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "payrollDefinitions" to-many relationship of EmployeeFile. */
    public List<PayrollDefinition> _queryEmployeeFile_PayrollDefinitions(long payrollDefinitionsEmployeeFileId) {
        synchronized (this) {
            if (employeeFile_PayrollDefinitionsQuery == null) {
                QueryBuilder<PayrollDefinition> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PayrollDefinitionsEmployeeFileId.eq(null));
                employeeFile_PayrollDefinitionsQuery = queryBuilder.build();
            }
        }
        Query<PayrollDefinition> query = employeeFile_PayrollDefinitionsQuery.forCurrentThread();
        query.setParameter(0, payrollDefinitionsEmployeeFileId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM PAYROLL_DEFINITION T");
            builder.append(" LEFT JOIN SAVE_RESULT T0 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PayrollDefinition loadCurrentDeep(Cursor cursor, boolean lock) {
        PayrollDefinition entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public PayrollDefinition loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PayrollDefinition> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PayrollDefinition> list = new ArrayList<PayrollDefinition>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PayrollDefinition> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PayrollDefinition> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
