package com.saulpower.GreenWireTest.database;

import java.util.List;
import de.greenrobot.dao.sync.GreenSync;
import com.google.gson.reflect.TypeToken;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.PickupAuthorization;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PICKUP_AUTHORIZATION.
*/
public class PickupAuthorizationDao extends AbstractDao<PickupAuthorization, Long> {

    public static final String TABLENAME = "PICKUP_AUTHORIZATION";

    /**
     * Properties of entity PickupAuthorization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ExternalID = new Property(0, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property Guid = new Property(1, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property PickupListStudentId = new Property(3, long.class, "pickupListStudentId", false, "PICKUP_LIST_STUDENT_ID");
        public final static Property AuthorizedPickupsStudentId = new Property(4, long.class, "authorizedPickupsStudentId", false, "AUTHORIZED_PICKUPS_STUDENT_ID");
        public final static Property TagString = new Property(5, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(6, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(7, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property AuthorizedPickupsPersonId = new Property(8, long.class, "authorizedPickupsPersonId", false, "AUTHORIZED_PICKUPS_PERSON_ID");
        public final static Property AuthorizedPickupsGuardianId = new Property(9, long.class, "authorizedPickupsGuardianId", false, "AUTHORIZED_PICKUPS_GUARDIAN_ID");
        public final static Property DateLastModified = new Property(10, String.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property SyncBaseId = new Property(11, Long.class, "syncBaseId", false, "SYNC_BASE_ID");
        public final static Property IsDeleted = new Property(12, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(13, Integer.class, "version", false, "VERSION");
        public final static Property StartDate = new Property(14, String.class, "startDate", false, "START_DATE");
        public final static Property Id = new Property(15, Long.class, "id", true, "_id");
        public final static Property DateCreated = new Property(16, String.class, "dateCreated", false, "DATE_CREATED");
        public final static Property RequiresConfirmation = new Property(17, Boolean.class, "requiresConfirmation", false, "REQUIRES_CONFIRMATION");
        public final static Property IsActive = new Property(18, Boolean.class, "isActive", false, "IS_ACTIVE");
        public final static Property Notes = new Property(19, String.class, "notes", false, "NOTES");
        public final static Property EndDate = new Property(20, String.class, "endDate", false, "END_DATE");
    };

    private DaoSession daoSession;

    private Query<PickupAuthorization> person_AuthorizedPickupsQuery;

    private Query<PickupAuthorization> student_PickupListQuery;

    private Query<PickupAuthorization> student_AuthorizedPickupsQuery;

    private Query<PickupAuthorization> guardian_AuthorizedPickupsQuery;

    public PickupAuthorizationDao(DaoConfig config) {
        super(config);
    }
    
    public PickupAuthorizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PICKUP_AUTHORIZATION' (" + //
                "'EXTERNAL_ID' TEXT," + // 0: externalID
                "'GUID' TEXT," + // 1: guid
                "'NAME' TEXT," + // 2: name
                "'PICKUP_LIST_STUDENT_ID' INTEGER NOT NULL ," + // 3: pickupListStudentId
                "'AUTHORIZED_PICKUPS_STUDENT_ID' INTEGER NOT NULL ," + // 4: authorizedPickupsStudentId
                "'TAG_STRING' TEXT," + // 5: tagString
                "'TENANT_ID' INTEGER," + // 6: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 7: saveResultSaveResultId
                "'AUTHORIZED_PICKUPS_PERSON_ID' INTEGER NOT NULL ," + // 8: authorizedPickupsPersonId
                "'AUTHORIZED_PICKUPS_GUARDIAN_ID' INTEGER NOT NULL ," + // 9: authorizedPickupsGuardianId
                "'DATE_LAST_MODIFIED' TEXT," + // 10: dateLastModified
                "'SYNC_BASE_ID' INTEGER REFERENCES 'SYNC_BASE'('SYNC_BASE_ID') ," + // 11: syncBaseId
                "'IS_DELETED' INTEGER," + // 12: isDeleted
                "'VERSION' INTEGER," + // 13: version
                "'START_DATE' TEXT," + // 14: startDate
                "'_id' INTEGER PRIMARY KEY ," + // 15: id
                "'DATE_CREATED' TEXT," + // 16: dateCreated
                "'REQUIRES_CONFIRMATION' INTEGER," + // 17: requiresConfirmation
                "'IS_ACTIVE' INTEGER," + // 18: isActive
                "'NOTES' TEXT," + // 19: notes
                "'END_DATE' TEXT);"); // 20: endDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PICKUP_AUTHORIZATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PickupAuthorization entity) {
        stmt.clearBindings();
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(1, externalID);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(2, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
        stmt.bindLong(4, entity.getPickupListStudentId());
        stmt.bindLong(5, entity.getAuthorizedPickupsStudentId());
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(6, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(7, tenantID);
        }
        stmt.bindLong(8, entity.getSaveResultSaveResultId());
        stmt.bindLong(9, entity.getAuthorizedPickupsPersonId());
        stmt.bindLong(10, entity.getAuthorizedPickupsGuardianId());
 
        String dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindString(11, dateLastModified);
        }
 
        Long syncBaseId = entity.getSyncBaseId();
        if (syncBaseId != null) {
            stmt.bindLong(12, syncBaseId);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(13, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(14, version);
        }
 
        String startDate = entity.getStartDate();
        if (startDate != null) {
            stmt.bindString(15, startDate);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(16, id);
        }
 
        String dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindString(17, dateCreated);
        }
 
        Boolean requiresConfirmation = entity.getRequiresConfirmation();
        if (requiresConfirmation != null) {
            stmt.bindLong(18, requiresConfirmation ? 1l: 0l);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(19, isActive ? 1l: 0l);
        }
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(20, notes);
        }
 
        String endDate = entity.getEndDate();
        if (endDate != null) {
            stmt.bindString(21, endDate);
        }
    }

    @Override
    protected void attachEntity(PickupAuthorization entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15);
    }    

    /** @inheritdoc */
    @Override
    public PickupAuthorization readEntity(Cursor cursor, int offset) {
        PickupAuthorization entity = new PickupAuthorization( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // externalID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // guid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.getLong(offset + 3), // pickupListStudentId
            cursor.getLong(offset + 4), // authorizedPickupsStudentId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // tagString
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // tenantID
            cursor.getLong(offset + 7), // saveResultSaveResultId
            cursor.getLong(offset + 8), // authorizedPickupsPersonId
            cursor.getLong(offset + 9), // authorizedPickupsGuardianId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // dateLastModified
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // syncBaseId
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isDeleted
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // version
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // startDate
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // id
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // dateCreated
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0, // requiresConfirmation
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0, // isActive
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // notes
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20) // endDate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PickupAuthorization entity, int offset) {
        entity.setExternalID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPickupListStudentId(cursor.getLong(offset + 3));
        entity.setAuthorizedPickupsStudentId(cursor.getLong(offset + 4));
        entity.setTagString(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTenantID(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 7));
        entity.setAuthorizedPickupsPersonId(cursor.getLong(offset + 8));
        entity.setAuthorizedPickupsGuardianId(cursor.getLong(offset + 9));
        entity.setDateLastModified(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSyncBaseId(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setIsDeleted(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setVersion(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setStartDate(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setId(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setDateCreated(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setRequiresConfirmation(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
        entity.setIsActive(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
        entity.setNotes(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setEndDate(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PickupAuthorization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PickupAuthorization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "authorizedPickups" to-many relationship of Person. */
    public List<PickupAuthorization> _queryPerson_AuthorizedPickups(long authorizedPickupsPersonId) {
        synchronized (this) {
            if (person_AuthorizedPickupsQuery == null) {
                QueryBuilder<PickupAuthorization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AuthorizedPickupsPersonId.eq(null));
                person_AuthorizedPickupsQuery = queryBuilder.build();
            }
        }
        Query<PickupAuthorization> query = person_AuthorizedPickupsQuery.forCurrentThread();
        query.setParameter(0, authorizedPickupsPersonId);
        return query.list();
    }

    /** Internal query to resolve the "pickupList" to-many relationship of Student. */
    public List<PickupAuthorization> _queryStudent_PickupList(long pickupListStudentId) {
        synchronized (this) {
            if (student_PickupListQuery == null) {
                QueryBuilder<PickupAuthorization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PickupListStudentId.eq(null));
                student_PickupListQuery = queryBuilder.build();
            }
        }
        Query<PickupAuthorization> query = student_PickupListQuery.forCurrentThread();
        query.setParameter(0, pickupListStudentId);
        return query.list();
    }

    /** Internal query to resolve the "authorizedPickups" to-many relationship of Student. */
    public List<PickupAuthorization> _queryStudent_AuthorizedPickups(long authorizedPickupsStudentId) {
        synchronized (this) {
            if (student_AuthorizedPickupsQuery == null) {
                QueryBuilder<PickupAuthorization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AuthorizedPickupsStudentId.eq(null));
                student_AuthorizedPickupsQuery = queryBuilder.build();
            }
        }
        Query<PickupAuthorization> query = student_AuthorizedPickupsQuery.forCurrentThread();
        query.setParameter(0, authorizedPickupsStudentId);
        return query.list();
    }

    /** Internal query to resolve the "authorizedPickups" to-many relationship of Guardian. */
    public List<PickupAuthorization> _queryGuardian_AuthorizedPickups(long authorizedPickupsGuardianId) {
        synchronized (this) {
            if (guardian_AuthorizedPickupsQuery == null) {
                QueryBuilder<PickupAuthorization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AuthorizedPickupsGuardianId.eq(null));
                guardian_AuthorizedPickupsQuery = queryBuilder.build();
            }
        }
        Query<PickupAuthorization> query = guardian_AuthorizedPickupsQuery.forCurrentThread();
        query.setParameter(0, authorizedPickupsGuardianId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM PICKUP_AUTHORIZATION T");
            builder.append(" LEFT JOIN SAVE_RESULT T0 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PickupAuthorization loadCurrentDeep(Cursor cursor, boolean lock) {
        PickupAuthorization entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public PickupAuthorization loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PickupAuthorization> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PickupAuthorization> list = new ArrayList<PickupAuthorization>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PickupAuthorization> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PickupAuthorization> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
    @Override
    protected void onPreInsertEntity(PickupAuthorization entity) {
        entity.insertBase(daoSession.getSyncBaseDao());
        entity.setSyncBaseId(entity.getSyncBaseId());
    }

    @Override
    protected void onPreLoadEntity(PickupAuthorization entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreRefreshEntity(PickupAuthorization entity) {
        entity.loadBase(daoSession.getSyncBaseDao(), entity.getSyncBaseId());
    }

    @Override
    protected void onPreUpdateEntity(PickupAuthorization entity) {
        entity.updateBase(daoSession.getSyncBaseDao());
    }

    @Override
    protected void onPreDeleteEntity(PickupAuthorization entity) {
        entity.deleteBase(daoSession.getSyncBaseDao());
    }

    static {
        GreenSync.registerListTypeToken("PickupAuthorization", new TypeToken<List<PickupAuthorization>>(){}.getType());
        GreenSync.registerTypeToken("PickupAuthorization", PickupAuthorization.class);
    }

}
