package com.saulpower.GreenWireTest.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.saulpower.GreenWireTest.database.RoleBase;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ROLE_BASE.
*/
public class RoleBaseDao extends AbstractDao<RoleBase, Long> {

    public static final String TABLENAME = "ROLE_BASE";

    /**
     * Properties of entity RoleBase.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ExternalID = new Property(0, String.class, "externalID", false, "EXTERNAL_ID");
        public final static Property Guid = new Property(1, String.class, "guid", false, "GUID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property CanManageOUs = new Property(3, Boolean.class, "canManageOUs", false, "CAN_MANAGE_OUS");
        public final static Property IsService = new Property(4, Boolean.class, "isService", false, "IS_SERVICE");
        public final static Property TagString = new Property(5, String.class, "tagString", false, "TAG_STRING");
        public final static Property TenantID = new Property(6, Long.class, "tenantID", false, "TENANT_ID");
        public final static Property SaveResultSaveResultId = new Property(7, long.class, "saveResultSaveResultId", false, "SAVE_RESULT_SAVE_RESULT_ID");
        public final static Property DateLastModified = new Property(8, Long.class, "dateLastModified", false, "DATE_LAST_MODIFIED");
        public final static Property IsManager = new Property(9, Boolean.class, "isManager", false, "IS_MANAGER");
        public final static Property IsDeleted = new Property(10, Boolean.class, "isDeleted", false, "IS_DELETED");
        public final static Property Version = new Property(11, Integer.class, "version", false, "VERSION");
        public final static Property IsAdmin = new Property(12, Boolean.class, "isAdmin", false, "IS_ADMIN");
        public final static Property Id = new Property(13, Long.class, "id", true, "_id");
        public final static Property RolesOUId = new Property(14, long.class, "rolesOUId", false, "ROLES_OUID");
        public final static Property DateCreated = new Property(15, Long.class, "dateCreated", false, "DATE_CREATED");
        public final static Property CanManageUsers = new Property(16, Boolean.class, "canManageUsers", false, "CAN_MANAGE_USERS");
        public final static Property IsSales = new Property(17, Boolean.class, "isSales", false, "IS_SALES");
        public final static Property IsActive = new Property(18, Boolean.class, "isActive", false, "IS_ACTIVE");
        public final static Property RolesOUBaseId = new Property(19, long.class, "rolesOUBaseId", false, "ROLES_OUBASE_ID");
    };

    private DaoSession daoSession;

    private Query<RoleBase> oU_RolesQuery;
    private Query<RoleBase> oUBase_RolesQuery;

    public RoleBaseDao(DaoConfig config) {
        super(config);
    }
    
    public RoleBaseDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ROLE_BASE' (" + //
                "'EXTERNAL_ID' TEXT," + // 0: externalID
                "'GUID' TEXT," + // 1: guid
                "'NAME' TEXT," + // 2: name
                "'CAN_MANAGE_OUS' INTEGER," + // 3: canManageOUs
                "'IS_SERVICE' INTEGER," + // 4: isService
                "'TAG_STRING' TEXT," + // 5: tagString
                "'TENANT_ID' INTEGER," + // 6: tenantID
                "'SAVE_RESULT_SAVE_RESULT_ID' INTEGER NOT NULL ," + // 7: saveResultSaveResultId
                "'DATE_LAST_MODIFIED' INTEGER," + // 8: dateLastModified
                "'IS_MANAGER' INTEGER," + // 9: isManager
                "'IS_DELETED' INTEGER," + // 10: isDeleted
                "'VERSION' INTEGER," + // 11: version
                "'IS_ADMIN' INTEGER," + // 12: isAdmin
                "'_id' INTEGER PRIMARY KEY ," + // 13: id
                "'ROLES_OUID' INTEGER NOT NULL ," + // 14: rolesOUId
                "'DATE_CREATED' INTEGER," + // 15: dateCreated
                "'CAN_MANAGE_USERS' INTEGER," + // 16: canManageUsers
                "'IS_SALES' INTEGER," + // 17: isSales
                "'IS_ACTIVE' INTEGER," + // 18: isActive
                "'ROLES_OUBASE_ID' INTEGER NOT NULL );"); // 19: rolesOUBaseId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ROLE_BASE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RoleBase entity) {
        stmt.clearBindings();
 
        String externalID = entity.getExternalID();
        if (externalID != null) {
            stmt.bindString(1, externalID);
        }
 
        String guid = entity.getGuid();
        if (guid != null) {
            stmt.bindString(2, guid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Boolean canManageOUs = entity.getCanManageOUs();
        if (canManageOUs != null) {
            stmt.bindLong(4, canManageOUs ? 1l: 0l);
        }
 
        Boolean isService = entity.getIsService();
        if (isService != null) {
            stmt.bindLong(5, isService ? 1l: 0l);
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(6, tagString);
        }
 
        Long tenantID = entity.getTenantID();
        if (tenantID != null) {
            stmt.bindLong(7, tenantID);
        }
        stmt.bindLong(8, entity.getSaveResultSaveResultId());
 
        Long dateLastModified = entity.getDateLastModified();
        if (dateLastModified != null) {
            stmt.bindLong(9, dateLastModified);
        }
 
        Boolean isManager = entity.getIsManager();
        if (isManager != null) {
            stmt.bindLong(10, isManager ? 1l: 0l);
        }
 
        Boolean isDeleted = entity.getIsDeleted();
        if (isDeleted != null) {
            stmt.bindLong(11, isDeleted ? 1l: 0l);
        }
 
        Integer version = entity.getVersion();
        if (version != null) {
            stmt.bindLong(12, version);
        }
 
        Boolean isAdmin = entity.getIsAdmin();
        if (isAdmin != null) {
            stmt.bindLong(13, isAdmin ? 1l: 0l);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(14, id);
        }
        stmt.bindLong(15, entity.getRolesOUId());
 
        Long dateCreated = entity.getDateCreated();
        if (dateCreated != null) {
            stmt.bindLong(16, dateCreated);
        }
 
        Boolean canManageUsers = entity.getCanManageUsers();
        if (canManageUsers != null) {
            stmt.bindLong(17, canManageUsers ? 1l: 0l);
        }
 
        Boolean isSales = entity.getIsSales();
        if (isSales != null) {
            stmt.bindLong(18, isSales ? 1l: 0l);
        }
 
        Boolean isActive = entity.getIsActive();
        if (isActive != null) {
            stmt.bindLong(19, isActive ? 1l: 0l);
        }
        stmt.bindLong(20, entity.getRolesOUBaseId());
    }

    @Override
    protected void attachEntity(RoleBase entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13);
    }    

    /** @inheritdoc */
    @Override
    public RoleBase readEntity(Cursor cursor, int offset) {
        RoleBase entity = new RoleBase( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // externalID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // guid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // canManageOUs
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isService
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // tagString
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // tenantID
            cursor.getLong(offset + 7), // saveResultSaveResultId
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8), // dateLastModified
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // isManager
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // isDeleted
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // version
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isAdmin
            cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13), // id
            cursor.getLong(offset + 14), // rolesOUId
            cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15), // dateCreated
            cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0, // canManageUsers
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0, // isSales
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0, // isActive
            cursor.getLong(offset + 19) // rolesOUBaseId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RoleBase entity, int offset) {
        entity.setExternalID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGuid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCanManageOUs(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setIsService(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setTagString(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTenantID(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setSaveResultSaveResultId(cursor.getLong(offset + 7));
        entity.setDateLastModified(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
        entity.setIsManager(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setIsDeleted(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setVersion(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setIsAdmin(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setId(cursor.isNull(offset + 13) ? null : cursor.getLong(offset + 13));
        entity.setRolesOUId(cursor.getLong(offset + 14));
        entity.setDateCreated(cursor.isNull(offset + 15) ? null : cursor.getLong(offset + 15));
        entity.setCanManageUsers(cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0);
        entity.setIsSales(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
        entity.setIsActive(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
        entity.setRolesOUBaseId(cursor.getLong(offset + 19));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RoleBase entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RoleBase entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "roles" to-many relationship of OU. */
    public List<RoleBase> _queryOU_Roles(long rolesOUId) {
        synchronized (this) {
            if (oU_RolesQuery == null) {
                QueryBuilder<RoleBase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RolesOUId.eq(null));
                oU_RolesQuery = queryBuilder.build();
            }
        }
        Query<RoleBase> query = oU_RolesQuery.forCurrentThread();
        query.setParameter(0, rolesOUId);
        return query.list();
    }

    /** Internal query to resolve the "roles" to-many relationship of OUBase. */
    public List<RoleBase> _queryOUBase_Roles(long rolesOUBaseId) {
        synchronized (this) {
            if (oUBase_RolesQuery == null) {
                QueryBuilder<RoleBase> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RolesOUBaseId.eq(null));
                oUBase_RolesQuery = queryBuilder.build();
            }
        }
        Query<RoleBase> query = oUBase_RolesQuery.forCurrentThread();
        query.setParameter(0, rolesOUBaseId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSaveResultDao().getAllColumns());
            builder.append(" FROM ROLE_BASE T");
            builder.append(" LEFT JOIN SAVE_RESULT T0 ON T.'SAVE_RESULT_SAVE_RESULT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RoleBase loadCurrentDeep(Cursor cursor, boolean lock) {
        RoleBase entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SaveResult saveResult = loadCurrentOther(daoSession.getSaveResultDao(), cursor, offset);
         if(saveResult != null) {
            entity.setSaveResult(saveResult);
        }

        return entity;    
    }

    public RoleBase loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RoleBase> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RoleBase> list = new ArrayList<RoleBase>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RoleBase> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RoleBase> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
